services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile-8.4       # set the wanted php version through the corresponding Dockerfile
    ports:
      - "8888:80"                      # map your computer port to the container port
    depends_on:
      - mysqldb
      - mariadb
    volumes:
      - ./html:/var/www/html           # map content of ./html in your computer to /var/www/html of container
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # map xdebug.ini into the container
      - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini # map error_reporting.ini into the container
  web2:
    build:
      context: .
      dockerfile: Dockerfile-8.2       # set the wanted php version through the corresponding Dockerfile
    ports:
      - "8880:80"                      # map your computer port to the container port
    depends_on:
      - mysqldb
      - mariadb
    volumes:
      - ./html:/var/www/html           # map content of ./html in your computer to /var/www/html of container
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # map xdebug.ini into the container
      - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini # map error_reporting.ini into the container
  mysqldb:
    image: mysql:9.4                   # set the mysql version you need for your project
    environment:
      - MYSQL_ROOT_PASSWORD=1234       # set mysql root pw or use: MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=blogdb          # this is optional, name a database to be created on image creation
      - MYSQL_USER=blog                # this is optional, name a user to be created on image create
      - MYSQL_PASSWORD=1234            # this is optional, password for the above created user
      - MYSQL_TCP_PORT=3306            # this is optional, default port is 3306
    volumes:
      - ./mysqldb_data:/var/lib/mysql  # map content of ./mysqldb_data in your computer to /var/lib/mysql of container
  mariadb:
    image: mariadb:10.6                # set the mariadb version you need for your project
    environment:
      - MYSQL_ROOT_PASSWORD=1234       # set mysql root pw or use: MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=blogdb          # this is optional, name a database to be created on image creation
      - MYSQL_USER=blog                # this is optional, name a user to be created on image create
      - MYSQL_PASSWORD=1234            # this is optional, password for the above created user
      - MYSQL_TCP_PORT=3306            # this is optional, default port is 3306
    volumes:
     - ./mariadb_data:/var/lib/mysql   # map content of ./mariadb_data in your computer to /var/lib/mysql of container
  phpmyadmin:
    image: phpmyadmin:5.2.2            # set the phpmyadmin version you need for your project
    ports:
      - "8080:80"                      # map your computer port to the container port
    depends_on:
      - mysqldb
      - mariadb
    environment:
      - PMA_HOSTS=mysqldb,mariadb      # if having only one host use PMA_HOST
      - PMA_PORTS=3306,3306            # if having only one port use PMA_PORT
      - UPLOAD_LIMIT=512M              # set upload_max_filesize and post_max_size
